apiVersion: v1
kind: Service
metadata:
  name: list-beer
  #namespace: tekton-pipelines
spec:
  ports:
    - port: 5000
      name: port
  selector:
    app: list-beer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: list-beer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: list-beer
  template:
    metadata:
      labels:
        app: list-beer
    spec:
      containers:
        - name: list-beer
          image: __IMAGE__
          ports:
            - containerPort: 5000
