apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: runpipeline
  #namespace: tekton-pipelines
spec:
  pipelineRef:
    name: build-and-deploy-pipeline
  resources:
    - name: git-repo
      resourceRef:
        name: git-repo
    - name: web-image
      resourceRef:
        name: image
