apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: runpipeline
  #namespace: tekton-pipelines
spec:
  pipelineRef:
    name: build-and-deploy-pipeline
  resources:
    - name: git-repo
      resourceRef:
        name: git-repo
    - name: web-image
      resourceRef:
        name: image
  params:
    - name: pathToYamlFileTest
      value: "appli/test_server.tavern.yaml"
    - name: appliUrl
      value: "list-beer.default.svc.cluster.local"
    - name: pathToYamlFile
      value: "tekton/listbeer.yml"
    - name: pathToContext
      value: "/workspace/git-repo/appli"
    - name: pathToDockerFile
      value: "Dockerfile"
