apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy-using-kubectl
  #namespace: tekton-pipelines
spec:
  inputs:
    resources:
      - name: git-repo
        type: git
      - name: image
        type: image
    params:
      - name: pathToYamlFile
        description: The path to the yaml file to deploy within the git source
        type: string
        #value: tekton/listbeer.yml
  steps:
    - name: update-yaml
      image: alpine
      command: ["sed"]
      args: [
          "-i",
          "-e",
          "s;__IMAGE__;$(inputs.resources.image.url);g",
          # "s;__IMAGE__;gcr.io/grounded-braid-232514/list-beer;g",
          "/workspace/git-repo/$(inputs.params.pathToYamlFile)",
        ]
    # "/workspace/git-repo/tekton/listbeer.yml",
    - name: run-kubectl
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        ["apply", "-f", "/workspace/git-repo/$(inputs.params.pathToYamlFile)"]
