on: push
name: testtekton
jobs:
  deploykube:
    name: deploy cluster K8s on GCP
    runs-on: ubuntu-latest
    steps:
    - name: GCP Authenticate
      uses: actions/gcloud/auth@master"
      with: 
        super_secret: ${{ secrets.AUTHGOOGLE }}
      env: 
        super_secret: ${{ secrets.AUTHGOOGLE }}
    - name: GCP add iam policy binding admin
      uses: actions/gcloud/cli@master
      with:
        args: projects add-iam-policy-binding grounded-braid-232514 --member serviceAccount:tekton@grounded-braid-232514.iam.gserviceaccount.com --role roles/storage.admin
    - name: GCP add iam policy binding dev
      uses: actions/gcloud/cli@master
      with:
        args: projects add-iam-policy-binding grounded-braid-232514 --member serviceAccount:tekton@grounded-braid-232514.iam.gserviceaccount.com --role roles/container.developer
    - name: GCP activ service googleapi
      uses: actions/gcloud/cli@master
      with:
        args: services enable container.googleapis.com
    - name: GCP activ service googleapi
      uses: actions/gcloud/cli@master
      with:
        args: services enable container.googleapis.com
    - name: GCP config zone
      uses: actions/gcloud/cli@master
      with:
        args: config set compute/zone europe-west3-a
    - name: GCP create cluster K8s
      uses: actions/gcloud/cli@master
      with:
        args: container clusters create cluster-tekton --service-account tekton@grounded-braid-232514.iam.gserviceaccount.com --scopes cloud-platform --machine-type n1-standard-2
  deploytekton:
    name: deploy Tekton on K8s
    needs: [deploykube]
    runs-on: ubuntu-latest
    steps:
    - name: GCP Authenticate
      uses: actions/gcloud/auth@master"
      env: 
        super_secret: ${{ secrets.AUTHGOOGLE }}
    - name: add tekton in K8s
      uses: steebchen/kubectl@master
      with:
        args: apply --filename https://storage.googleapis.com/tekton-releases/latest/release.yaml
    - name: add dashboard tekton in K8s
      uses: steebchen/kubectl@master
      with:
        args: apply --filename https://github.com/tektoncd/dashboard/releases/download/v0.1.1/release.yaml
    - name: create rolebinding in K8s
      uses: steebchen/kubectl@master
      with:
        args: create rolebinding --serviceaccount default:default --clusterrole admin default-admin
  deployappli:
    name: deploy appli and test it with Tekton
    needs: [deploykube,deploytekton]
    runs-on: ubuntu-latest
    steps:
    - name: GCP Authenticate
      uses: actions/gcloud/auth@master"
      with: 
        super_secret: ${{ secrets.AUTHGOOGLE }}
    - name: create pipelineresource
      uses: steebchen/kubectl@master
      with:
        args: apply -f ./tekton/gitrepo.yml
    - name: create taskBPD
      uses: steebchen/kubectl@master
      with:
        args: apply -f ./tekton/taskBPD.yml
    - name: create taskDK
      uses: steebchen/kubectl@master
      with:
        args: apply -f ./tekton/taskDK.yml
    - name: create tasktest
      uses: steebchen/kubectl@master
      with:
        args: apply -f ./tekton/tasktest.yml
    - name: create pipeline
      uses: steebchen/kubectl@master
      with:
        args: apply -f ./tekton/pipeline.yml
    - name: create pipelinerun
      uses: steebchen/kubectl@master
      with:
        args: apply -f ./tekton/pipelinerun.yml
